import type { AppModel } from '@goldensheepai/sheplang-language';

const typeMap: Record<string, string> = {
  'text': 'string',
  'number': 'number',
  'yes/no': 'boolean',
  'id': 'string',
  'date': 'string',
  'email': 'string'
};

function toTsType(s: string): string {
  return typeMap[s] ?? 'unknown';
}

export function templateTsConfig(): string {
  return `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "strict": true,
    "jsx": "react-jsx",
    "noEmit": true
  },
  "include": ["**/*.ts", "**/*.tsx"]
}`;
}

export function templateModels(app: AppModel): { path: string; content: string }[] {
  const files: { path: string; content: string }[] = [];
  
  // Generate TypeScript interfaces
  app.datas.forEach((d) => {
    const fields = d.fields.map((f: { name: string; type: string }) => `  ${f.name}: ${toTsType(f.type)};`).join('\n');
    const rules = d.rules.length ? `// rules:\n// ${d.rules.map((r: string) => `- ${r}`).join('\n// ')}` : `// rules: (none)`;
    const tsContent = `// Auto-generated by ShepLang
export interface ${d.name} {
  id?: string;\n${fields}
}\n\n${rules}
`;
    files.push({ path: `models/${d.name}.ts`, content: tsContent });
  });
  
  // Generate Prisma schema
  const prismaModels = app.datas.map((d) => {
    const prismaFields = [
      `  id     String @id @default(uuid())`,
      ...d.fields.map((f: { name: string; type: string }) => {
        const prismaType = toPrismaType(f.type);
        return `  ${f.name} ${prismaType}`;
      }),
      `  createdAt DateTime @default(now())`,
      `  updatedAt DateTime @updatedAt`
    ].join('\n');
    
    return `model ${d.name} {\n${prismaFields}\n}`;
  }).join('\n\n');
  
  const prismaContent = `// Auto-generated by ShepLang
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

${prismaModels}
`;
  
  files.push({ path: `prisma/schema.prisma`, content: prismaContent });
  
  return files;
}

function toPrismaType(shepType: string): string {
  const map: Record<string, string> = {
    'text': 'String',
    'number': 'Int',
    'yes/no': 'Boolean',
    'id': 'String',
    'date': 'DateTime',
    'email': 'String'
  };
  return map[shepType] || 'String';
}

export function templateActions(app: AppModel): { path: string; content: string }[] {
  return app.actions.map((a) => {
    const paramsSig = a.params.map((p) => `${p.name}${p.type ? `: ${toTsType(p.type)}` : ': any'}`).join(', ');
    
    const imports: string[] = [];
    const ops = a.ops.map((op) => {
      if (op.kind === 'add' && op.fields && op.data) {
        if (!imports.includes(op.data)) {
          imports.push(`import type { ${op.data} } from '../models/${op.data}';`);
        }
        const fields = Object.entries(op.fields)
          .map(([k, v]) => {
            // Check if value is a parameter reference or literal
            const isParam = a.params.some(p => p.name === v);
            return `    ${k}: ${isParam ? v : JSON.stringify(v)}`;
          })
          .join(',\n');
        return `  // Create new ${op.data}
  const new${op.data} = await fetch('/api/${op.data.toLowerCase()}s', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
${fields}
    })
  }).then(res => res.json());`;
      }
      if (op.kind === 'show' && op.view) {
        return `  // Navigate to ${op.view}
  return { redirect: '/${op.view.toLowerCase()}' };`;
      }
      if (op.kind === 'call') {
        // Phase 3: API call code generation
        const method = op.method;
        const path = op.path;
        const fields = op.fields || [];
        const hasBody = method !== 'GET' && method !== 'DELETE' && fields.length > 0;
        
        return `  // API call: ${method} ${path}
  const callResponse = await fetch('/api${path}', {
    method: '${method}',
    headers: { 'Content-Type': 'application/json' }${hasBody ? `,
    body: JSON.stringify({ ${fields.join(', ')} })` : ''}
  });
  
  if (!callResponse.ok) {
    throw new Error(\`API call failed: \${callResponse.statusText}\`);
  }
  
  const callResult = await callResponse.json();`;
      }
      if (op.kind === 'load') {
        // Phase 3: Data loading code generation
        const method = op.method;
        const path = op.path;
        const variable = op.variable;
        
        return `  // Load data: ${method} ${path}
  const loadResponse = await fetch('/api${path}', {
    method: '${method}',
    headers: { 'Content-Type': 'application/json' }
  });
  
  if (!loadResponse.ok) {
    throw new Error(\`Load failed: \${loadResponse.statusText}\`);
  }
  
  const ${variable} = await loadResponse.json();`;
      }
      if (op.kind === 'workflow') {
        // Phase 3: Workflow Engine code generation
        const steps = op.steps || [];
        const workflowCode = steps.map((step: any, index: number) => {
          const stepBody = step.body?.map((stmt: any) => {
            if (stmt.kind === 'call') {
              const hasBody = stmt.method !== 'GET' && stmt.method !== 'DELETE' && stmt.fields && stmt.fields.length > 0;
              return `    const response${index} = await fetch('/api${stmt.path}', {
      method: '${stmt.method}',
      headers: { 'Content-Type': 'application/json' }${hasBody ? `,
      body: JSON.stringify({ ${stmt.fields.join(', ')} })` : ''}
    });
    if (!response${index}.ok) throw new Error('${step.name} failed');`;
            }
            return `    // ${stmt.kind}`;
          }).join('\n') || '';
          
          return `  // Step: ${step.name}
  try {
${stepBody}
  } catch (error) {
    console.error('Step ${step.name} failed:', error);${op.errorHandler ? `
    return await ${op.errorHandler}();` : `
    throw error;`}
  }`;
        }).join('\n\n');
        
        return `  // Workflow: ${steps.map((s: any) => s.name).join(' → ')}
${workflowCode}`;
      }
      if (op.kind === 'raw' && 'text' in op) {
        return `  // Custom operation\n  console.log(${JSON.stringify(op.text || '')});`;
      }
      // Handle other statement kinds (update, delete, etc.)
      return `  // TODO: Implement ${op.kind} operation\n  console.log('${op.kind}:', ${JSON.stringify(op)});`;
    }).join('\n\n');

    const importsStr = imports.length ? imports.join('\n') + '\n\n' : '';

    const content = `// Auto-generated by ShepLang
${importsStr}export async function ${a.name}(${paramsSig}) {
${ops || '  // no-ops'}
}
`;
    return { path: `actions/${a.name}.ts`, content };
  });
}

export function templateViews(app: AppModel): { path: string; content: string }[] {
  return app.views.map((v) => {
    const entityName = v.list || 'Item';
    const entityVar = entityName.toLowerCase() + 's';
    
    const imports = [
      `import { useState, useEffect } from 'react';`,
      v.list ? `import type { ${entityName} } from '../models/${entityName}';` : ''
    ].filter(Boolean).join('\n');
    
    const stateDecl = v.list ? `const [${entityVar}, set${entityName}s] = useState<${entityName}[]>([]);` : '';
    
    const loadData = v.list ? `
  useEffect(() => {
    // Load ${entityName} data from API
    fetch('/api/${entityVar}')
      .then(res => res.json())
      .then(data => set${entityName}s(data))
      .catch(err => console.error('Failed to load ${entityVar}:', err));
  }, []);` : '';
    
    const listRender = v.list ? `
      <div className="space-y-4">
        <h2 className="text-2xl font-bold">${v.name}</h2>
        <ul className="divide-y divide-gray-200">
          {${entityVar}.map((item) => (
            <li key={item.id || Math.random()} className="py-4">
              {JSON.stringify(item)}
            </li>
          ))}
        </ul>
      </div>` : `<div className="p-4">
        <h2 className="text-2xl font-bold">${v.name}</h2>
      </div>`;
    
    const buttons = v.buttons.map((b) => 
      `    <button
        onClick={() => handle${b.action}()}
        className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700"
      >
        ${b.label}
      </button>`
    ).join('\n');
    
    const handlers = v.buttons.map((b) =>
      `  const handle${b.action} = () => {
    // TODO: Implement ${b.action}
    console.log('${b.action} triggered');
  };`
    ).join('\n\n');
    
    const content = `// Auto-generated by ShepLang
${imports}

export function ${v.name}() {
  ${stateDecl}${loadData}

${handlers}

  return (
    <div className="container mx-auto p-4">
${listRender}
      <div className="mt-4 flex gap-2">
${buttons}
      </div>
    </div>
  );
}
`;
    return { path: `views/${v.name}.tsx`, content };
  });
}

export function templateIndex(app: AppModel): { path: string; content: string } {
  const imports: string[] = [];
  app.views.forEach((v) => imports.push(`import { ${v.name} } from './views/${v.name}';`));
  app.actions.forEach((a) => imports.push(`import { ${a.name} } from './actions/${a.name}';`));

  const run = `export async function run() {
  console.log("Starting ${app.name}…");
  ${app.views.map((v) => `if (${v.name}) ${v.name}();`).join('\n  ')}
}`;

  return {
    path: `index.ts`,
    content: `// Auto-generated by ShepLang
${imports.join('\n')}

${run}
`
  };
}
