packages:
  - "packages/language"
  - "packages/cli"
  - "packages/runtime"
  - "../adapters/*"
  - "examples"
  - "e2e"
  # Not in alpha release:
  # - "packages/compiler"
  # - "packages/transpiler"
