/**
 * Entity Generator for ShepLang
 * 
 * Generates .shep entity files from questionnaire data
 */

import { EntityDefinition, ProjectQuestionnaire } from '../wizard/types';

export class EntityGenerator {
  /**
   * Generate a ShepLang entity file
   */
  public generateEntity(entity: EntityDefinition, questionnaire: ProjectQuestionnaire): string {
    const content = `# ${entity.name} Entity
# Generated by ShepLang Wizard for ${questionnaire.projectName}

data ${entity.name}:
  fields:
${this.generateFields(entity.fields)}
${this.generateRelationships(entity, questionnaire.entities)}
${this.generateBackgroundJobs(entity, questionnaire)}
`;

    return content;
  }

  /**
   * Generate field definitions
   */
  private generateFields(fields: any[]): string {
    return fields.map(field => {
      const required = field.required ? ' # Required' : '';
      return `    ${field.name}: ${this.mapFieldType(field.type)}${required}`;
    }).join('\n');
  }

  /**
   * Generate relationship definitions
   */
  private generateRelationships(entity: EntityDefinition, allEntities: EntityDefinition[]): string {
    const relationships: string[] = [];

    // Auto-detect relationships based on field names
    for (const field of entity.fields) {
      const fieldName = field.name.toLowerCase();

      // Check if this field references another entity
      for (const otherEntity of allEntities) {
        if (otherEntity.name !== entity.name && fieldName.includes(otherEntity.name.toLowerCase())) {
          relationships.push(`    ${field.name}: reference ${otherEntity.name}`);
        }
      }
    }

    // Add common relationships
    if (entity.name.toLowerCase() === 'order' && allEntities.some(e => e.name.toLowerCase() === 'user')) {
      relationships.push('    user: reference User # Who placed the order');
    }

    if (entity.name.toLowerCase() === 'user' && allEntities.some(e => e.name.toLowerCase() === 'team')) {
      relationships.push('    team: reference Team # Team membership');
    }

    return relationships.length > 0
      ? '\n  # Relationships\n' + relationships.join('\n')
      : '';
  }

  /**
   * Generate background jobs for entity
   */
  private generateBackgroundJobs(entity: EntityDefinition, questionnaire: ProjectQuestionnaire): string {
    const jobs: string[] = [];

    // Common jobs based on entity type
    const entityName = entity.name.toLowerCase();

    if (entityName.includes('user') || entityName.includes('customer')) {
      jobs.push(`
# Send welcome email when user is created
job sendWelcomeEmail(${entityName}):
  trigger: ${entity.name} created
  action: call SendGrid with ${entityName}.email, template="welcome"
`);
    }

    if (entityName.includes('order') || entityName.includes('payment')) {
      jobs.push(`
# Process payment when order is created
job processPayment(order):
  trigger: Order created
  action: call Stripe with order.amount, order.customerEmail
`);
    }

    if (entityName.includes('subscription')) {
      jobs.push(`
# Handle subscription renewal
job renewSubscription(subscription):
  trigger: Subscription updated
  when: subscription.status == "renewal_due"
  action: call Stripe with subscription.id, action="renew"
`);
    }

    if (questionnaire.projectType === 'content-platform' && entityName.includes('post')) {
      jobs.push(`
# Notify followers of new post
job notifyFollowers(post):
  trigger: Post created
  action: call SendGrid with post.author.followers, template="new_post"
`);
    }

    return jobs.join('');
  }

  /**
   * Map field types to ShepLang types
   */
  private mapFieldType(type: string): string {
    const typeMap: Record<string, string> = {
      'text': 'text',
      'number': 'number',
      'date': 'date',
      'yes/no': 'yes/no',
      'image': 'image',
      'email': 'text',
      'url': 'text',
      'phone': 'text',
      'currency': 'number',
      'percentage': 'number',
      'rating': 'number',
      'boolean': 'yes/no'
    };

    return typeMap[type] || 'text';
  }

  /**
   * Generate validation rules for entity
   */
  public generateValidationRules(entity: EntityDefinition): string {
    const rules: string[] = [];

    for (const field of entity.fields) {
      if (field.type === 'email') {
        rules.push(`  validate ${field.name} is email`);
      }

      if (field.type === 'number' && field.name.toLowerCase().includes('price')) {
        rules.push(`  validate ${field.name} > 0`);
      }

      if (field.required) {
        rules.push(`  validate ${field.name} is required`);
      }
    }

    return rules.length > 0 ? rules.join('\n') : '';
  }

  /**
   * Generate sample data for entity
   */
  public generateSampleData(entity: EntityDefinition): string {
    const samples: string[] = [];

    // Generate 2-3 sample records
    const sampleCount = Math.min(3, Math.max(2, entity.fields.length));

    for (let i = 1; i <= sampleCount; i++) {
      const sampleFields = entity.fields.map(field => {
        return this.generateSampleFieldValue(field, i, entity);
      }).join(', ');

      samples.push(`  add ${entity.name} with ${sampleFields}`);
    }

    return samples.join('\n');
  }

  /**
   * Generate sample field value
   */
  private generateSampleFieldValue(field: any, index: number, entity: EntityDefinition): string {
    const fieldName = field.name.toLowerCase();

    switch (field.type) {
      case 'text':
        if (fieldName.includes('email')) {
          return `${field.name}: "sample${index}@example.com"`;
        } else if (fieldName.includes('name')) {
          return `${field.name}: "Sample ${entity.name} ${index}"`;
        } else if (fieldName.includes('title')) {
          return `${field.name}: "Sample Title ${index}"`;
        } else {
          return `${field.name}: "Sample ${field.name} ${index}"`;
        }

      case 'number':
        if (fieldName.includes('price')) {
          return `${field.name}: ${index * 9.99}`;
        } else if (fieldName.includes('amount')) {
          return `${field.name}: ${index * 100}`;
        } else {
          return `${field.name}: ${index}`;
        }

      case 'date':
        return `${field.name}: "${new Date(Date.now() - index * 24 * 60 * 60 * 1000).toISOString().split('T')[0]}"`;

      case 'yes/no':
        return `${field.name}: ${index % 2 === 0 ? 'yes' : 'no'}`;

      case 'image':
        return `${field.name}: "https://example.com/image${index}.jpg"`;

      default:
        return `${field.name}: "Sample value ${index}"`;
    }
  }

  /**
   * Generate CRUD operations for entity
   */
  public generateCrudOperations(entity: EntityDefinition): string {
    const entityName = entity.name;
    const entityNameLower = entityName.toLowerCase();

    return `
# Create ${entityNameLower}
action create${entityName}(${this.generateActionParams(entity.fields)}):
  call POST "/${entityNameLower}" with ${this.generateFieldList(entity.fields)}
  load GET "/${entityNameLower}" into ${entityNameLower}List
  show ${entityName}List

# View ${entityNameLower} details
action view${entityName}(id):
  load GET "/${entityNameLower}/:id" into ${entityNameLower}
  show ${entityName}Detail

# Update ${entityNameLower}
action update${entityName}(id, ${this.generateActionParams(entity.fields)}):
  call PUT "/${entityNameLower}/:id" with id, ${this.generateFieldList(entity.fields)}
  load GET "/${entityNameLower}" into ${entityNameLower}List
  show ${entityName}List

# Delete ${entityNameLower}
action delete${entityName}(id):
  call DELETE "/${entityNameLower}/:id"
  load GET "/${entityNameLower}" into ${entityNameLower}List
  show ${entityName}List
`;
  }

  /**
   * Generate action parameters
   */
  private generateActionParams(fields: any[]): string {
    const requiredFields = fields.filter(f => f.required && f.name !== 'id' && f.name !== 'createdAt');
    return requiredFields.map(f => f.name).join(', ');
  }

  /**
   * Generate field list for API calls
   */
  private generateFieldList(fields: any[]): string {
    const requiredFields = fields.filter(f => f.required && f.name !== 'id' && f.name !== 'createdAt');
    return requiredFields.map(f => f.name).join(', ');
  }
}
