/**
 * Flow Generator for ShepLang
 * 
 * Generates .shep flow files from questionnaire data
 */

import { ProjectFeature, ProjectQuestionnaire, Integration } from '../wizard/types';

export class FlowGenerator {
  /**
   * Generate authentication flow
   */
  public generateAuthFlow(questionnaire: ProjectQuestionnaire): string {
    const hasRoles = questionnaire.roleType !== 'single-user';
    
    return `# Authentication Flow
# Generated by ShepLang Wizard for ${questionnaire.projectName}

flow Authentication:
  steps:
    # Step 1: User Registration
    step registerUser:
      action: registerUser(email, password, name)
      success: verifyEmail
      failure: showRegistrationError

    # Step 2: Email Verification
    step verifyEmail:
      action: sendVerificationEmail(email)
      success: waitForVerification
      failure: showVerificationError

    # Step 3: Wait for Email Verification
    step waitForVerification:
      condition: emailVerified
      success: completeRegistration
      timeout: resendVerification

    # Step 4: Complete Registration
    step completeRegistration:
      action: createProfile(email, name)
      success: ${hasRoles ? 'assignRole' : 'showDashboard'}
      failure: showProfileError

    # Step 5: Assign Role (if multi-role)
    ${hasRoles ? `step assignRole:
      action: assignUserRole(email, defaultRole)
      success: showDashboard
      failure: showRoleError` : ''}

    # Step 6: Show Dashboard
    step showDashboard:
      action: show Dashboard

    # Error Handlers
    step showRegistrationError:
      action: show RegisterForm with error="Registration failed"

    step showVerificationError:
      action: show VerifyEmail with error="Verification failed"

    step resendVerification:
      action: sendVerificationEmail(email)
      success: waitForVerification
      failure: showVerificationError

    step showProfileError:
      action: show ProfileForm with error="Profile creation failed"

    ${hasRoles ? `step showRoleError:
      action: show RoleSelection with error="Role assignment failed"` : ''}

# Login Flow
flow Login:
  steps:
    step loginUser:
      action: loginUser(email, password)
      success: validateSession
      failure: showLoginError

    step validateSession:
      action: validateUserSession(email)
      success: showDashboard
      failure: showSessionError

    step showLoginError:
      action: show LoginForm with error="Invalid credentials"

    step showSessionError:
      action: show LoginForm with error="Session validation failed"

# Logout Flow
flow Logout:
  steps:
    step clearSession:
      action: clearUserSession()
      success: showLogin
      failure: showLogoutError

    step showLogin:
      action: show LoginForm

    step showLogoutError:
      action: show Dashboard with error="Logout failed"
`;
  }

  /**
   * Generate feature-specific flow
   */
  public generateFeatureFlow(feature: ProjectFeature, questionnaire: ProjectQuestionnaire): string {
    const featureName = this.sanitizeFlowName(feature.name);
    
    // Generate flow based on feature type
    if (this.isCrudFeature(feature.name)) {
      return this.generateCrudFlow(feature, questionnaire);
    } else if (this.isWorkflowFeature(feature.name)) {
      return this.generateWorkflowFlow(feature, questionnaire);
    } else {
      return this.generateGenericFlow(feature, questionnaire);
    }
  }

  /**
   * Generate CRUD flow
   */
  private generateCrudFlow(feature: ProjectFeature, questionnaire: ProjectQuestionnaire): string {
    const entityName = this.extractEntityName(feature.name);
    const entityNameLower = entityName.toLowerCase();
    
    return `# ${feature.name} Flow
# Generated by ShepLang Wizard for ${questionnaire.projectName}

flow ${this.sanitizeFlowName(feature.name)}:
  steps:
    # Step 1: List ${entityName}s
    step list${entityName}s:
      action: load GET "/${entityNameLower}" into ${entityNameLower}List
      success: show${entityName}List
      failure: showListError

    # Step 2: Show ${entityName} List
    step show${entityName}List:
      action: show ${entityName}List
      onSelection: view${entityName}

    # Step 3: View ${entityName} Details
    step view${entityName}:
      action: load GET "/${entityNameLower}/:id" into ${entityNameLower}
      success: show${entityName}Detail
      failure: showDetailError

    # Step 4: Show ${entityName} Detail
    step show${entityName}Detail:
      action: show ${entityName}Detail
      onCreate: create${entityName}
      onEdit: edit${entityName}
      onDelete: delete${entityName}

    # Step 5: Create ${entityName}
    step create${entityName}:
      action: show Create${entityName}Form
      onSubmit: save${entityName}

    # Step 6: Save ${entityName}
    step save${entityName}:
      action: call POST "/${entityNameLower}" with formData
      success: list${entityName}s
      failure: showCreateError

    # Step 7: Edit ${entityName}
    step edit${entityName}:
      action: load GET "/${entityNameLower}/:id" into ${entityNameLower}
      success: showEdit${entityName}Form
      failure: showEditError

    # Step 8: Update ${entityName}
    step update${entityName}:
      action: call PUT "/${entityNameLower}/:id" with formData
      success: list${entityName}s
      failure: showUpdateError

    # Step 9: Delete ${entityName}
    step delete${entityName}:
      action: show DeleteConfirmation
      onConfirm: confirmDelete${entityName}

    # Step 10: Confirm Delete
    step confirmDelete${entityName}:
      action: call DELETE "/${entityNameLower}/:id"
      success: list${entityName}s
      failure: showDeleteError

    # Error Handlers
    step showListError:
      action: show ${entityName}List with error="Failed to load ${entityNameLower}s"

    step showDetailError:
      action: show ${entityName}List with error="Failed to load ${entityNameLower} details"

    step showCreateError:
      action: show Create${entityName}Form with error="Failed to create ${entityNameLower}"

    step showEditError:
      action: show ${entityName}List with error="Failed to load ${entityNameLower} for editing"

    step showUpdateError:
      action: show Edit${entityName}Form with error="Failed to update ${entityNameLower}"

    step showDeleteError:
      action: show ${entityName}List with error="Failed to delete ${entityNameLower}"
`;
  }

  /**
   * Generate workflow flow
   */
  private generateWorkflowFlow(feature: ProjectFeature, questionnaire: ProjectQuestionnaire): string {
    return `# ${feature.name} Workflow
# Generated by ShepLang Wizard for ${questionnaire.projectName}

flow ${this.sanitizeFlowName(feature.name)}:
  steps:
    # Step 1: Initialize Workflow
    step initialize:
      action: createWorkflowInstance("${feature.name}")
      success: processData
      failure: showInitializationError

    # Step 2: Process Data
    step processData:
      action: processWorkflowData(workflowId, inputData)
      success: validateResults
      failure: showProcessingError

    # Step 3: Validate Results
    step validateResults:
      action: validateWorkflowResults(workflowId, results)
      success: completeWorkflow
      failure: handleValidationErrors

    # Step 4: Complete Workflow
    step completeWorkflow:
      action: markWorkflowComplete(workflowId)
      success: showSuccess
      failure: showCompletionError

    # Step 5: Handle Validation Errors
    step handleValidationErrors:
      action: show ValidationErrors with errors
      onRetry: processData
      onCancel: cancelWorkflow

    # Step 6: Cancel Workflow
    step cancelWorkflow:
      action: markWorkflowCancelled(workflowId)
      success: showDashboard
      failure: showCancellationError

    # Step 7: Show Success
    step showSuccess:
      action: show WorkflowSuccess with workflowId

    # Error Handlers
    step showInitializationError:
      action: show WorkflowForm with error="Failed to initialize workflow"

    step showProcessingError:
      action: show WorkflowForm with error="Failed to process data"

    step showCompletionError:
      action: show WorkflowForm with error="Failed to complete workflow"

    step showCancellationError:
      action: show WorkflowForm with error="Failed to cancel workflow"
`;
  }

  /**
   * Generate generic flow
   */
  private generateGenericFlow(feature: ProjectFeature, questionnaire: ProjectQuestionnaire): string {
    return `# ${feature.name} Flow
# Generated by ShepLang Wizard for ${questionnaire.projectName}

flow ${this.sanitizeFlowName(feature.name)}:
  steps:
    # Step 1: Initialize Feature
    step initialize:
      action: initialize${this.sanitizeFlowName(feature.name)}()
      success: executeFeature
      failure: showInitializationError

    # Step 2: Execute Feature
    step executeFeature:
      action: execute${this.sanitizeFlowName(feature.name)}(parameters)
      success: processResults
      failure: showExecutionError

    # Step 3: Process Results
    step processResults:
      action: process${this.sanitizeFlowName(feature.name)}Results(results)
      success: showResults
      failure: showProcessingError

    # Step 4: Show Results
    step showResults:
      action: show ${this.sanitizeFlowName(feature.name)}Results

    # Error Handlers
    step showInitializationError:
      action: show ${this.sanitizeFlowName(feature.name)}Form with error="Initialization failed"

    step showExecutionError:
      action: show ${this.sanitizeFlowName(feature.name)}Form with error="Execution failed"

    step showProcessingError:
      action: show ${this.sanitizeFlowName(feature.name)}Form with error="Processing failed"
`;
  }

  /**
   * Generate webhook flow for integrations
   */
  public generateWebhookFlow(questionnaire: ProjectQuestionnaire): string {
    const integrations = questionnaire.integrations;
    
    return `# Webhook Integrations Flow
# Generated by ShepLang Wizard for ${questionnaire.projectName}

flow WebhookIntegrations:
  steps:
    # Step 1: Receive Webhook
    step receiveWebhook:
      action: parseWebhookPayload(request)
      success: validateWebhook
      failure: showWebhookError

    # Step 2: Validate Webhook
    step validateWebhook:
      action: validateWebhookSignature(payload, signature)
      success: processWebhook
      failure: showValidationError

    # Step 3: Process Webhook
    step processWebhook:
      action: processWebhookData(payload)
      success: updateDatabase
      failure: showProcessingError

    # Step 4: Update Database
    step updateDatabase:
      action: call POST "/webhooks/update" with processedData
      success: sendResponse
      failure: showDatabaseError

    # Step 5: Send Response
    step sendResponse:
      action: respondToWebhook(status: "success", data: response)
      success: complete
      failure: showResponseError

    # Integration-specific handlers
    ${this.generateIntegrationHandlers(integrations)}

    # Error Handlers
    step showWebhookError:
      action: respondToWebhook(status: "error", message: "Invalid webhook")

    step showValidationError:
      action: respondToWebhook(status: "error", message: "Invalid signature")

    step showProcessingError:
      action: respondToWebhook(status: "error", message: "Processing failed")

    step showDatabaseError:
      action: respondToWebhook(status: "error", message: "Database update failed")

    step showResponseError:
      action: respondToWebhook(status: "error", message: "Response failed")
`;
  }

  /**
   * Generate integration-specific handlers
   */
  private generateIntegrationHandlers(integrations: Integration[]): string {
    const handlers: string[] = [];
    
    for (const integration of integrations) {
      switch (integration.service) {
        case 'Stripe':
          handlers.push(`
    # Stripe webhook handler
    step handleStripeWebhook:
      action: processStripeEvent(payload.eventType, payload.data)
      success: updateDatabase
      failure: showStripeError

    step showStripeError:
      action: respondToWebhook(status: "error", message: "Stripe processing failed")
          `);
          break;
          
        case 'SendGrid':
          handlers.push(`
    # SendGrid webhook handler
    step handleSendGridWebhook:
      action: processSendGridEvent(payload.event)
      success: updateDatabase
      failure: showSendGridError

    step showSendGridError:
      action: respondToWebhook(status: "error", message: "SendGrid processing failed")
          `);
          break;
          
        case 'Clerk':
          handlers.push(`
    # Clerk webhook handler
    step handleClerkWebhook:
      action: processClerkEvent(payload.type, payload.data)
      success: updateDatabase
      failure: showClerkError

    step showClerkError:
      action: respondToWebhook(status: "error", message: "Clerk processing failed")
          `);
          break;
      }
    }
    
    return handlers.join('');
  }

  /**
   * Helper methods
   */
  private sanitizeFlowName(name: string): string {
    return name
      .replace(/[^a-zA-Z0-9]/g, '')
      .replace(/^[a-z]/, c => c.toUpperCase());
  }

  private isCrudFeature(featureName: string): boolean {
    const crudKeywords = ['manage', 'create', 'edit', 'delete', 'list', 'view', 'update'];
    return crudKeywords.some(keyword => featureName.toLowerCase().includes(keyword));
  }

  private isWorkflowFeature(featureName: string): boolean {
    const workflowKeywords = ['workflow', 'process', 'approval', 'pipeline', 'automation'];
    return workflowKeywords.some(keyword => featureName.toLowerCase().includes(keyword));
  }

  private extractEntityName(featureName: string): string {
    // Try to extract entity name from feature name
    const words = featureName.split(' ');
    for (const word of words) {
      if (word.length > 2 && !['manage', 'create', 'edit', 'delete', 'list', 'view', 'update'].includes(word.toLowerCase())) {
        return word.charAt(0).toUpperCase() + word.slice(1);
      }
    }
    return 'Item';
  }
}
