/**
 * Integration Generator for ShepLang
 * 
 * Generates .shep integration files from questionnaire data
 */

import { Integration, ProjectQuestionnaire } from '../wizard/types';

export class IntegrationGenerator {
  /**
   * Generate integration file
   */
  public generateIntegration(integration: Integration, questionnaire: ProjectQuestionnaire): string {
    switch (integration.service) {
      case 'Stripe':
        return this.generateStripeIntegration(questionnaire);
      case 'PayPal':
        return this.generatePayPalIntegration(questionnaire);
      case 'SendGrid':
        return this.generateSendGridIntegration(questionnaire);
      case 'Resend':
        return this.generateResendIntegration(questionnaire);
      case 'AWS S3':
        return this.generateS3Integration(questionnaire);
      case 'Cloudinary':
        return this.generateCloudinaryIntegration(questionnaire);
      case 'Clerk':
        return this.generateClerkIntegration(questionnaire);
      case 'Auth0':
        return this.generateAuth0Integration(questionnaire);
      default:
        return this.generateGenericIntegration(integration, questionnaire);
    }
  }

  /**
   * Generate Stripe integration
   */
  private generateStripeIntegration(questionnaire: ProjectQuestionnaire): string {
    return `# Stripe Payment Integration
# Generated by ShepLang Wizard for ${questionnaire.projectName}

integration Stripe:
  config:
    apiKey: env.STRIPE_API_KEY
    webhookSecret: env.STRIPE_WEBHOOK_SECRET
    mode: "production" # or "development"

  # Payment Processing
  action createPayment(amount, currency = "usd", description):
    call Stripe.createPaymentIntent with amount, currency, description
    return paymentIntent

  action capturePayment(paymentIntentId):
    call Stripe.capturePaymentIntent with paymentIntentId
    return payment

  action refundPayment(paymentId, amount):
    call Stripe.createRefund with paymentId, amount
    return refund

  # Customer Management
  action createCustomer(email, name):
    call Stripe.createCustomer with email, name
    return customer

  action updateCustomer(customerId, updates):
    call Stripe.updateCustomer with customerId, updates
    return customer

  # Subscription Management
  action createSubscription(customerId, priceId):
    call Stripe.createSubscription with customerId, priceId
    return subscription

  action cancelSubscription(subscriptionId):
    call Stripe.cancelSubscription with subscriptionId
    return subscription

  # Webhook Handlers
  webhook handleStripeWebhook:
    on "payment_intent.succeeded":
      updateOrderStatus paymentIntent.metadata.orderId, "paid"
      sendReceipt paymentIntent.receipt_email

    on "payment_intent.payment_failed":
      updateOrderStatus paymentIntent.metadata.orderId, "payment_failed"
      notifyPaymentFailure paymentIntent.metadata.orderId

    on "invoice.payment_succeeded":
      extendSubscription invoice.subscription
      sendPaymentConfirmation invoice.customer_email

    on "customer.subscription.deleted":
      cancelUserAccess subscription.customer
      sendCancellationNotice subscription.customer

  # Utility Functions
  action updateOrderStatus(orderId, status):
    call PUT "/orders/:id/status" with orderId, status

  action sendReceipt(email):
    call SendGrid.sendReceipt with email

  action notifyPaymentFailure(orderId):
    call SendGrid.sendPaymentFailure with orderId

  action extendSubscription(subscriptionId):
    call PUT "/subscriptions/:id/extend" with subscriptionId

  action sendPaymentConfirmation(email):
    call SendGrid.sendPaymentConfirmation with email

  action cancelUserAccess(customerId):
    call PUT "/users/:id/access" with customerId, access: false

  action sendCancellationNotice(customerId):
    call SendGrid.sendCancellationNotice with customerId
`;
  }

  /**
   * Generate SendGrid integration
   */
  private generateSendGridIntegration(questionnaire: ProjectQuestionnaire): string {
    return `# SendGrid Email Integration
# Generated by ShepLang Wizard for ${questionnaire.projectName}

integration SendGrid:
  config:
    apiKey: env.SENDGRID_API_KEY
    fromEmail: env.SENDGRID_FROM_EMAIL
    fromName: "${questionnaire.projectName}"

  # Email Templates
  templates:
    welcome: "d-welcome-template"
    receipt: "d-receipt-template"
    passwordReset: "d-password-reset-template"
    verification: "d-email-verification-template"
    notification: "d-notification-template"

  # Send Email
  action sendEmail(to, templateId, data):
    call SendGrid.sendTemplate with to, templateId, data
    return message

  # Specific Email Types
  action sendWelcomeEmail(email, name):
    data = {
      name: name,
      appName: "${questionnaire.projectName}",
      loginUrl: env.APP_URL + "/login"
    }
    sendEmail email, templates.welcome, data

  action sendReceipt(email, orderDetails):
    data = {
      orderNumber: orderDetails.id,
      amount: orderDetails.amount,
      items: orderDetails.items,
      supportEmail: env.SUPPORT_EMAIL
    }
    sendEmail email, templates.receipt, data

  action sendPasswordReset(email, resetToken):
    data = {
      resetUrl: env.APP_URL + "/reset-password?token=" + resetToken,
      expiryHours: 24
    }
    sendEmail email, templates.passwordReset, data

  action sendVerificationEmail(email, verificationToken):
    data = {
      verificationUrl: env.APP_URL + "/verify-email?token=" + verificationToken,
      appName: "${questionnaire.projectName}"
    }
    sendEmail email, templates.verification, data

  action sendNotification(email, title, message, actionUrl = null):
    data = {
      title: title,
      message: message,
      actionUrl: actionUrl,
      appName: "${questionnaire.projectName}"
    }
    sendEmail email, templates.notification, data

  # Bulk Email
  action sendBulkEmail(recipients, templateId, data):
    for recipient in recipients:
      sendEmail recipient.email, templateId, data
    return sentCount

  # Email Analytics
  action getEmailStats(messageId):
    call SendGrid.getMessageStats with messageId
    return stats

  action unsubscribeUser(email):
    call SendGrid.unsubscribe with email
    return success
`;
  }

  /**
   * Generate AWS S3 integration
   */
  private generateS3Integration(questionnaire: ProjectQuestionnaire): string {
    return `# AWS S3 Storage Integration
# Generated by ShepLang Wizard for ${questionnaire.projectName}

integration S3:
  config:
    accessKeyId: env.AWS_ACCESS_KEY_ID
    secretAccessKey: env.AWS_SECRET_ACCESS_KEY
    region: env.AWS_REGION
    bucket: env.S3_BUCKET_NAME

  # File Upload
  action uploadFile(file, key = null, folder = "uploads"):
    if not key:
      key = folder + "/" + generateUUID() + "-" + file.name
    
    call S3.upload with file, key
    return {
      url: env.S3_CDN_URL + "/" + key,
      key: key,
      size: file.size,
      type: file.type
    }

  # File Download
  action downloadFile(key):
    call S3.download with key
    return file

  # Delete File
  action deleteFile(key):
    call S3.delete with key
    return success

  # Generate Presigned URL
  action getUploadUrl(key, expiresIn = 3600):
    call S3.getPresignedUploadUrl with key, expiresIn
    return url

  action getDownloadUrl(key, expiresIn = 3600):
    call S3.getPresignedDownloadUrl with key, expiresIn
    return url

  # Folder Operations
  action listFiles(folder = "", maxKeys = 1000):
    call S3.list with folder, maxKeys
    return files

  action deleteFolder(folder):
    files = listFiles folder
    for file in files:
      deleteFile file.key
    return deletedCount

  # Image Processing (with S3 + Lambda)
  action processImage(key, transformations = {}):
    # Resize, crop, optimize images
    call S3.processImage with key, transformations
    return processedUrl

  action createThumbnail(key, width = 200, height = 200):
    transformations = {
      resize: { width: width, height: height },
      crop: "center",
      quality: 80
    }
    processImage key, transformations

  # Backup Operations
  action backupDatabase():
    # Create database backup and upload to S3
    backupFile = createDatabaseBackup()
    uploadFile backupFile, "backups/" + formatDate(backupFile.createdAt)
    return backupUrl

  action restoreBackup(backupKey):
    backupFile = downloadFile backupKey
    restoreFromBackup backupFile
    return success

  # Utility Functions
  action generateUUID():
    call crypto.randomUUID
    return uuid

  action formatDate(date):
    call date.format with date, "YYYY-MM-DD-HH-mm-ss"
    return formatted
`;
  }

  /**
   * Generate Clerk integration
   */
  private generateClerkIntegration(questionnaire: ProjectQuestionnaire): string {
    return `# Clerk Authentication Integration
# Generated by ShepLang Wizard for ${questionnaire.projectName}

integration Clerk:
  config:
    apiKey: env.CLERK_API_KEY
    jwtKey: env.CLERK_JWT_KEY
    frontendApi: env.CLERK_FRONTEND_API

  # User Authentication
  action authenticateUser(token):
    call Clerk.verifyToken with token
    return user

  action registerUser(email, password, name = null):
    call Clerk.createUser with email, password, name
    return user

  action loginUser(email, password):
    call Clerk.authenticate with email, password
    return session

  action logoutUser(sessionId):
    call Clerk.revokeSession with sessionId
    return success

  # User Management
  action updateUser(userId, updates):
    call Clerk.updateUser with userId, updates
    return user

  action deleteUser(userId):
    call Clerk.deleteUser with userId
    return success

  # Session Management
  action getUserSessions(userId):
    call Clerk.getUserSessions with userId
    return sessions

  action revokeAllSessions(userId):
    call Clerk.revokeAllSessions with userId
    return success

  # Role Management
  action assignRole(userId, role):
    call Clerk.setMetadata with userId, { role: role }
    return user

  action getUserRole(userId):
    user = call Clerk.getUser with userId
    return user.metadata.role

  # Organization Management (if team-based)
  action createOrganization(name, slug):
    call Clerk.createOrganization with name, slug
    return organization

  action addOrganizationMember(organizationId, userId, role = "basic_member"):
    call Clerk.addOrganizationMember with organizationId, userId, role
    return membership

  action removeOrganizationMember(organizationId, userId):
    call Clerk.removeOrganizationMember with organizationId, userId
    return success

  # Webhook Handlers
  webhook handleClerkWebhook:
    on "user.created":
      createUserProfile user.data
      sendWelcomeEmail user.data.email_address

    on "user.updated":
      syncUserProfile user.data

    on "user.deleted":
      cleanupUserData user.data

    on "session.created":
      trackUserLogin user.data

    on "session.ended":
      trackUserLogout user.data

  # Utility Functions
  action createUserProfile(clerkUser):
    call POST "/users" with {
      clerkId: clerkUser.id,
      email: clerkUser.email_address,
      name: clerkUser.first_name + " " + clerkUser.last_name
    }

  action syncUserProfile(clerkUser):
    call PUT "/users/by-clerk-id/" + clerkUser.id with {
      email: clerkUser.email_address,
      name: clerkUser.first_name + " " + clerkUser.last_name
    }

  action cleanupUserData(clerkUser):
    call DELETE "/users/by-clerk-id/" + clerkUser.id

  action trackUserLogin(clerkUser):
    call POST "/analytics/login" with userId: clerkUser.id

  action trackUserLogout(clerkUser):
    call POST "/analytics/logout" with userId: clerkUser.id
`;
  }

  /**
   * Generate generic integration template
   */
  private generateGenericIntegration(integration: Integration, questionnaire: ProjectQuestionnaire): string {
    return `# ${integration.service} Integration
# Generated by ShepLang Wizard for ${questionnaire.projectName}

integration ${integration.service}:
  config:
    apiKey: env.${integration.service.toUpperCase()}_API_KEY
    # Add additional config variables as needed

  # Basic Actions
  action initialize():
    call ${integration.service}.connect
    return connection

  action sendData(data):
    call ${integration.service}.send with data
    return response

  action receiveData():
    call ${integration.service}.receive
    return data

  # Webhook Handler
  webhook handle${integration.service}Webhook:
    on "event":
      processWebhookEvent data

  # Utility Functions
  action processWebhookEvent(data):
    # Process incoming webhook data
    log "Received ${integration.service} webhook: " + data
`;
  }

  /**
   * Generate PayPal integration
   */
  private generatePayPalIntegration(questionnaire: ProjectQuestionnaire): string {
    return `# PayPal Payment Integration
# Generated by ShepLang Wizard for ${questionnaire.projectName}

integration PayPal:
  config:
    clientId: env.PAYPAL_CLIENT_ID
    clientSecret: env.PAYPAL_CLIENT_SECRET
    mode: "sandbox" # or "live"

  action createPayment(amount, currency = "USD"):
    call PayPal.createOrder with amount, currency
    return order

  action capturePayment(orderId):
    call PayPal.captureOrder with orderId
    return payment

  action refundPayment(paymentId):
    call PayPal.refundPayment with paymentId
    return refund
`;
  }

  /**
   * Generate Resend integration
   */
  private generateResendIntegration(questionnaire: ProjectQuestionnaire): string {
    return `# Resend Email Integration
# Generated by ShepLang Wizard for ${questionnaire.projectName}

integration Resend:
  config:
    apiKey: env.RESEND_API_KEY
    fromEmail: env.RESEND_FROM_EMAIL

  action sendEmail(to, subject, html):
    call Resend.sendEmail with to, subject, html
    return message

  action sendWelcomeEmail(email, name):
    sendEmail email, "Welcome to ${questionnaire.projectName}!", welcomeTemplate(name)
`;
  }

  /**
   * Generate Cloudinary integration
   */
  private generateCloudinaryIntegration(questionnaire: ProjectQuestionnaire): string {
    return `# Cloudinary Image Integration
# Generated by ShepLang Wizard for ${questionnaire.projectName}

integration Cloudinary:
  config:
    cloudName: env.CLOUDINARY_CLOUD_NAME
    apiKey: env.CLOUDINARY_API_KEY
    apiSecret: env.CLOUDINARY_API_SECRET

  action uploadImage(file, folder = "uploads"):
    call Cloudinary.upload with file, folder
    return {
      url: result.secure_url,
      publicId: result.public_id
    }

  action createThumbnail(publicId, width = 200, height = 200):
    call Cloudinary.generateThumbnail with publicId, width, height
    return thumbnailUrl
`;
  }

  /**
   * Generate Auth0 integration
   */
  private generateAuth0Integration(questionnaire: ProjectQuestionnaire): string {
    return `# Auth0 Authentication Integration
# Generated by ShepLang Wizard for ${questionnaire.projectName}

integration Auth0:
  config:
    domain: env.AUTH0_DOMAIN
    clientId: env.AUTH0_CLIENT_ID
    clientSecret: env.AUTH0_CLIENT_SECRET

  action authenticateUser(token):
    call Auth0.verifyToken with token
    return user

  action createUser(email, password):
    call Auth0.createUser with email, password
    return user
`;
  }
}
