packages:
  - sheplang/packages/*
  - adapters/*
  - sheplang/shepkit
  - sheplang/sandbox
  - sheplang/examples
  - sheplang/playground
  - sheplang/e2e

ignoredBuiltDependencies:
  - esbuild
  - unrs-resolver
