packages:
  - sheplang/packages/*
  - adapters/*
  - sheplang/shepkit
  - sheplang/playground
  - sheplang/examples
  - sheplang/e2e
  - playground-vite
  - extension

ignoredBuiltDependencies:
  - esbuild
  - unrs-resolver
