// Auto-generated by ShepLang
import { Dashboard } from './views/Dashboard';
import { CreateTodo } from './actions/CreateTodo';

export async function run() {
  console.log("Starting MyTodos…");
  if (Dashboard) Dashboard();
}
