// Auto-generated by ShepLang
import { useState, useEffect } from 'react';
import type { Todo } from '../models/Todo';

export function Dashboard() {
  const [todos, setTodos] = useState<Todo[]>([]);
  useEffect(() => {
    // Load Todo data from API
    fetch('/api/todos')
      .then(res => res.json())
      .then(data => setTodos(data))
      .catch(err => console.error('Failed to load todos:', err));
  }, []);

  const handleCreateTodo = () => {
    // TODO: Implement CreateTodo
    console.log('CreateTodo triggered');
  };

  return (
    <div className="container mx-auto p-4">

      <div className="space-y-4">
        <h2 className="text-2xl font-bold">Dashboard</h2>
        <ul className="divide-y divide-gray-200">
          {todos.map((item) => (
            <li key={item.id || Math.random()} className="py-4">
              {JSON.stringify(item)}
            </li>
          ))}
        </ul>
      </div>
      <div className="mt-4 flex gap-2">
    <button
        onClick={() => handleCreateTodo()}
        className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700"
      >
        Add Task
      </button>
      </div>
    </div>
  );
}
