// Auto-generated by ShepLang
import express from 'express';
import cors from 'cors';
import todosRoutes from './routes/todos';

const app = express();
const PORT = process.env.PORT || 3001;

// Middleware
app.use(cors());
app.use(express.json());

// Routes
  app.use('/api/todos', todosRoutes);

// Health check
app.get('/health', (req, res) => {
  res.json({ status: 'ok', app: 'MyTodos' });
});

// Start server
app.listen(PORT, () => {
  console.log(`MyTodos API server running on port ${PORT}`);
});

export default app;
