/**
 * Build Configuration Generator
 * 
 * Reads .env file and generates a config.ts file with the company API key
 * This runs before TypeScript compilation
 */

const fs = require('fs');
const path = require('path');

// Read .env file
const envPath = path.join(__dirname, '..', '.env');
let apiKey = '';

if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf-8');
  const match = envContent.match(/ANTHROPIC_API_KEY=(.+)/);
  if (match) {
    apiKey = match[1].trim();
    console.log('✓ Found API key in .env file');
  } else {
    console.warn('⚠ No ANTHROPIC_API_KEY found in .env file');
  }
} else {
  console.warn('⚠ No .env file found - AI features will require user API key');
}

// Generate config.ts
const configContent = `/**
 * Build-time configuration
 * ⚠ THIS FILE IS AUTO-GENERATED - DO NOT EDIT
 * Generated by scripts/build-config.js
 */

// Company API key (bundled at build time)
export const ANTHROPIC_COMPANY_KEY: string | undefined = ${apiKey ? `'${apiKey}'` : 'undefined'};
`;

const configPath = path.join(__dirname, '..', 'src', 'ai', 'config.ts');
fs.writeFileSync(configPath, configContent, 'utf-8');

if (apiKey) {
  console.log('✓ Generated src/ai/config.ts with company API key');
} else {
  console.log('✓ Generated src/ai/config.ts (no company key - fallback mode)');
}
