// Auto-generated by ShepLang
import type { Todo } from '../models/Todo';

export async function CreateTodo(title: any) {
  // Create new Todo
  const newTodo = await fetch('/api/todos', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
    title: title,
    done: "false"
    })
  }).then(res => res.json());

  // Navigate to Dashboard
  return { redirect: '/dashboard' };
}
