// Auto-generated by ShepLang
import { Router } from 'express';
import { PrismaClient } from '../../src/generated/prisma';

const router = Router();
const prisma = new PrismaClient();

// GET all Todos
router.get('/', async (req, res) => {
  try {
    const items = await prisma.todo.findMany({
      orderBy: { createdAt: 'desc' }
    });
    res.json(items);
  } catch (error) {
    console.error('Error fetching todos:', error);
    res.status(500).json({ error: 'Failed to fetch todos' });
  }
});

// GET single Todo by ID
router.get('/:id', async (req, res) => {
  try {
    const item = await prisma.todo.findUnique({
      where: { id: req.params.id }
    });
    if (!item) {
      return res.status(404).json({ error: 'Todo not found' });
    }
    res.json(item);
  } catch (error) {
    console.error('Error fetching Todo:', error);
    res.status(500).json({ error: 'Failed to fetch Todo' });
  }
});

// POST create new Todo
router.post('/', async (req, res) => {
  try {
    const item = await prisma.todo.create({
      data: req.body
    });
    res.status(201).json(item);
  } catch (error) {
    console.error('Error creating Todo:', error);
    res.status(500).json({ error: 'Failed to create Todo' });
  }
});

// PUT update Todo
router.put('/:id', async (req, res) => {
  try {
    const item = await prisma.todo.update({
      where: { id: req.params.id },
      data: req.body
    });
    res.json(item);
  } catch (error) {
    console.error('Error updating Todo:', error);
    res.status(500).json({ error: 'Failed to update Todo' });
  }
});

// DELETE Todo
router.delete('/:id', async (req, res) => {
  try {
    await prisma.todo.delete({
      where: { id: req.params.id }
    });
    res.status(204).send();
  } catch (error) {
    console.error('Error deleting Todo:', error);
    res.status(500).json({ error: 'Failed to delete Todo' });
  }
});

export default router;
