'use client';

import { useState } from 'react';

interface CodeDisplayProps {
  fileName: string;
  content: string;
}

export function CodeDisplay({ fileName, content }: CodeDisplayProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const getLanguage = (fileName: string) => {
    const ext = fileName.split('.').pop();
    switch (ext) {
      case 'tsx':
      case 'jsx':
        return 'typescript-react';
      case 'ts':
        return 'typescript';
      case 'js':
        return 'javascript';
      case 'json':
        return 'json';
      case 'prisma':
        return 'prisma';
      case 'md':
        return 'markdown';
      default:
        return 'text';
    }
  };

  const lineCount = content.split('\n').length;

  return (
    <div className="h-full flex flex-col">
      {/* File Header */}
      <div className="flex items-center justify-between px-6 py-3 border-b bg-gray-50">
        <div className="flex items-center gap-3">
          <span className="text-sm font-mono text-gray-700">{fileName}</span>
          <span className="text-xs text-gray-500">
            {lineCount} lines • {getLanguage(fileName)}
          </span>
        </div>
        <button
          onClick={handleCopy}
          className="px-3 py-1 text-sm bg-white border border-gray-300 rounded hover:bg-gray-50 transition-colors flex items-center gap-2"
        >
          {copied ? (
            <>
              <span>✓</span>
              <span>Copied!</span>
            </>
          ) : (
            <>
              <span>📋</span>
              <span>Copy</span>
            </>
          )}
        </button>
      </div>

      {/* Code Content */}
      <div className="flex-1 overflow-auto bg-gray-900">
        <pre className="p-6 text-sm font-mono text-gray-100 leading-relaxed">
          <code>{content}</code>
        </pre>
      </div>

      {/* Footer Info */}
      <div className="px-6 py-2 border-t bg-gray-50 text-xs text-gray-600">
        <div className="flex items-center gap-4">
          <span>✓ Production-ready TypeScript</span>
          <span>•</span>
          <span>Generated by @goldensheepai/sheplang-compiler</span>
          <span>•</span>
          <span>Ready to deploy</span>
        </div>
      </div>
    </div>
  );
}
